// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projectEF;

#nullable disable

namespace projectEF.Migrations
{
    [DbContext(typeof(TareasContext))]
    partial class TareasContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("projectEF.Models.Categoria", b =>
                {
                    b.Property<Guid>("CategoriaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.HasKey("CategoriaID");

                    b.ToTable("Categoria", (string)null);

                    b.HasData(
                        new
                        {
                            CategoriaID = new Guid("d24f36a0-89e7-4e99-ac6f-8f7818716939"),
                            Descripcion = "Las actividades que están todavía pendientes de hacer.",
                            Nombre = "Actividades pendientes",
                            Peso = 20
                        },
                        new
                        {
                            CategoriaID = new Guid("d24f36a0-89e7-4e99-ac6f-8f7818716940"),
                            Descripcion = "Las actividades que se tienen que hacer personalmente.",
                            Nombre = "Actividades personales",
                            Peso = 50
                        });
                });

            modelBuilder.Entity("projectEF.Models.Tarea", b =>
                {
                    b.Property<Guid>("TareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("PrioridadTarea")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UrlArchivo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TareaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Tarea", (string)null);

                    b.HasData(
                        new
                        {
                            TareaId = new Guid("b83f34bf-af22-493a-bd0e-415788ce4163"),
                            CategoriaId = new Guid("d24f36a0-89e7-4e99-ac6f-8f7818716939"),
                            Descripcion = "Hay que hacer la compra en el mercadona.",
                            FechaCreacion = new DateTime(2024, 6, 14, 11, 20, 58, 108, DateTimeKind.Local).AddTicks(8203),
                            PrioridadTarea = 1,
                            Titulo = "Hacer la compra",
                            UrlArchivo = "https://cdn.businessinsider.es/sites/navi.axelspringer.es/public/media/image/2022/11/mujer-mirando-lista-compra-2880589.jpg?tf=3840x"
                        },
                        new
                        {
                            TareaId = new Guid("b83f34bf-af22-493a-bd0e-415788ce4174"),
                            CategoriaId = new Guid("d24f36a0-89e7-4e99-ac6f-8f7818716940"),
                            Descripcion = "Salir a correr 15 minutos o correr en la cinta.",
                            FechaCreacion = new DateTime(2024, 6, 14, 11, 20, 58, 108, DateTimeKind.Local).AddTicks(8254),
                            PrioridadTarea = 2,
                            Titulo = "Hacer deporte",
                            UrlArchivo = "https://media.revistagq.com/photos/641c645781245672268fff7a/16:9/w_2560%2Cc_limit/1036780592"
                        });
                });

            modelBuilder.Entity("projectEF.Models.Tarea", b =>
                {
                    b.HasOne("projectEF.Models.Categoria", "Categoria")
                        .WithMany("Tareas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("projectEF.Models.Categoria", b =>
                {
                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
